export const MEDICATION = [
  { item: 5,  label: 'Activated charcoal' },
  { item: 6,  label: 'Antacid chewable (Antacil®)' },
  { item: 7,  label: 'Domperidone 10mg (Adult)' },
  { item: 8,  label: 'Domperidone Syrup 5mg (Child)' },
  { item: 9,  label: 'Dimenhydrinate 50mg' },
  { item: 10, label: 'ENO (Sodium Bicarbonate)' },
  { item: 11, label: 'Eye irrigator' },
  { item: 12, label: 'CPM + Phenylephrine (Sulidine®)' },
  { item: 13, label: 'Loratadine 10mg (Adult)' },
  { item: 14, label: 'Cetirizine Syrup 5mg (Child)' },
  { item: 15, label: 'ORS (Oreda®)' },
  { item: 16, label: 'Paracetamol 500mg (Adult)' },
  { item: 17, label: 'Paracetamol 120mg/5ml (Child)' },
  { item: 18, label: 'Vapex solution' },
];

export const EQUIPMENT = [
  { item: 19, label: 'Tensoplast assorted (3 size)' },
  { item: 20, label: 'Transpore 2.5cm x 1.5m' },
  { item: 21, label: 'Adhesive wound closure (2 size)' },
  { item: 22, label: 'Alcohol pad' },
  { item: 23, label: 'Betadine solution' },
  { item: 24, label: 'Gauze roll 3" + Triangular' },
  { item: 25, label: 'Burn gel 10x10cm' },
  { item: 26, label: 'Biohazard bag 18x20"' },
  { item: 27, label: 'Cotton wool' },
  { item: 28, label: 'CPR pocket mask' },
  { item: 29, label: 'Disposable gloves' },
  { item: 30, label: 'Elastic bandage 7.5cm x 4.5m' },
  { item: 31, label: 'Safety pins' },
  { item: 32, label: 'Scissor' },
  { item: 33, label: 'Surgical mask' },
  { item: 34, label: 'Thermometers (non-mercury)' },
  { item: 35, label: 'Tweezer' },
  { item: 36, label: 'Gauze pad 3x3", 4x4"' },
];
